language: objective-c
 
before_install:
 # Make sure mono is installed,
# - wget http://origin-download.mono-project.com/archive/3.2.7/macos-10-x86/MonoFramework-MDK-3.2.7.macos10.xamarin.x86.pkg
# - hdid MonoFramework-MDK-3.2.7.macos10.xamarin.x86.dmg
# - sudo installer -pkg "/Volumes/Mono Framework MDK 3.2.7/MonoFramework-MDK-3.2.7.macos10.xamarin.x86.pkg" -target /
 - sudo apt-get install mono-devel mono-gmcs 
 - export EnableNuGetPackageRestore=true


script:
  - xbuild TestTravis.sln

